 # 類貪食蛇v1.2
 
 ## v1.1 新增自訂矩形大小
 ## v1.2 美化外觀，改善螺旋矩陣算法。

In [ ]:
import numpy as np
from ipywidgets import interact 

In [ ]:
length = int(input('Length:'))
width = int(input('Width:'))

In [528]:
l1 = ['●','●', '●', '●', 'ღ'] 
a1 = np.zeros((width, length), dtype=int)

In [529]:
r = 0
a = 0
flag = 1
## flag 1 = right[0,1]
## flag 2 = down[1,0]
## flag 3 = left[0,-1]
## flag 4 = up[-1,0]

In [530]:
def turn(r,a,flag):
    if flag % 4 == 1:
        a -= 1 
        r += 1
    if flag % 4 == 2:
        r -= 1
        a -= 1
    if flag % 4 == 3:
        a += 1
        r -= 1
    if flag % 4 == 0:
        r += 1
        a += 1
    
    flag += 1

    return r, a, flag
    
def after_turn(r,a,flag):
    if flag % 4 == 1:
        a += 1
    if flag % 4 == 2:
        r += 1
    if flag % 4 == 3:
        a -= 1
    if flag % 4 == 0:
        r -= 1    
    
    return r, a, flag

for i in range(1, length * width + 1):
    if( r == width or a == length or r < 0 or a < 0):
        r, a, flag = turn(r,a,flag)
        a1[r][a] = i
        r, a, flag = after_turn(r,a,flag)
        
    elif(a1[r][a] == 0):
        a1[r][a] = i
        if flag % 4 == 1:
            a += 1
        if flag % 4 == 2:
            r += 1
        if flag % 4 == 3:
            a -= 1
        if flag % 4 == 0:
            r -= 1
       
    elif(a1[r][a] > 0):
        r, a, flag = turn(r,a,flag)
        a1[r][a] = i
        r, a, flag = after_turn(r,a,flag)

        

In [531]:
print(a1)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 46  47  48  49  50  51  52  53  54  55  56  57  58  59  16]
 [ 45  84  85  86  87  88  89  90  91  92  93  94  95  60  17]
 [ 44  83 114 115 116 117 118 119 120 121 122 123  96  61  18]
 [ 43  82 113 136 137 138 139 140 141 142 143 124  97  62  19]
 [ 42  81 112 135 150 149 148 147 146 145 144 125  98  63  20]
 [ 41  80 111 134 133 132 131 130 129 128 127 126  99  64  21]
 [ 40  79 110 109 108 107 106 105 104 103 102 101 100  65  22]
 [ 39  78  77  76  75  74  73  72  71  70  69  68  67  66  23]
 [ 38  37  36  35  34  33  32  31  30  29  28  27  26  25  24]]


In [532]:
def e04(x = 1):
    a2 = np.zeros((width + 2, length + 2), dtype=str)
    for l1_index in range(5):
        for i in range(1,width + 1):
            for j in range(1,length + 1):
                if(a1[i-1][j-1] == x + l1_index):
                    a2[i][j] = l1[l1_index]
                elif(not a2[i][j]):
                    a2[i][j] = '  '
                    
    for i in range(1,width+1):
        a2[i][0] = '︳'
    for j in range(1,length+1):
        a2[0][j] = '-'
    for i in range(1,width+1):
        a2[i][length + 1] = '︳'
    for j in range(1,length+1):
        a2[width + 1][j] = '-'
    a2[0][0] = '*'
    a2[width+1][0] = '*'
    a2[0][length+1] = '*'
    a2[width+1][length+1] = '*'
    
    for i in range(width + 2):
        for j in range(length + 2):
             print(a2[i][j], end = '   ')   
        print('\n')
    

In [533]:
interact(e04, x = (1 ,length * width - 4))

interactive(children=(IntSlider(value=1, description='x', max=146, min=1), Output()), _dom_classes=('widget-in…

<function __main__.e04(x=1)>