In [1]:
import numpy as np
import pandas as pd

In [2]:
dabDataset = np.load('data/dabs.npy')
tposeDataset = np.load('data/tposes.npy')
otherDataset = np.load('data/other.npy')

In [3]:
dabDataset[0]

array([[5.8832416e+02, 2.9433704e+02, 7.2265184e-01],
       [5.8239331e+02, 3.5126093e+02, 8.0205584e-01],
       [5.0984329e+02, 3.4919385e+02, 7.5316119e-01],
       [4.1784265e+02, 3.1985785e+02, 8.1164622e-01],
       [3.6101605e+02, 2.9243521e+02, 8.0296052e-01],
       [6.5091376e+02, 3.6097537e+02, 6.4161348e-01],
       [6.3724268e+02, 2.7274924e+02, 7.8188539e-01],
       [4.9614203e+02, 2.4154723e+02, 8.3243752e-01],
       [5.4315808e+02, 6.4114813e+02, 4.4807938e-01],
       [4.8636816e+02, 6.2938318e+02, 3.6906898e-01],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [6.0191382e+02, 6.4702966e+02, 3.8946095e-01],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [5.7648334e+02, 2.7475522e+02, 6.1822432e-01],
       [6.0389270e+02, 2.8454663e+02, 4.1854110e-01],
       [5.5686536e+02, 2.6891223e+02, 2.7014270e-01],
       [6.1959991e+02, 2.924

In [4]:
dabDataset.shape

(14, 25, 3)

In [5]:
dabDataset[0].shape

(25, 3)

# Adding our Labels

In [6]:
labels = ["Nose", "Neck", "RShoulder", "RElbow", "RWrist", "LShoulder", "LElbow",
 "LWrist", "MidHip", "RHip", "RKnee", "RAnkle", "LHip", "LKnee", "LAnkle",
 "REye", "LEye", "REar", "LEar", "LBigToe", "LSmallToe", "LHeel", "RBigToe",
 "RSmallToe", "RHeel", "Background"]

In [7]:
properLabels = []
for label in labels:
    properLabels.append(label + 'X')
    properLabels.append(label + 'Y')
    properLabels.append(label + 'Confidence')

In [8]:
import csv

with open('data/dabs.csv', 'w+') as dabcsv:
    dabwriter = csv.writer(dabcsv, delimiter=',')
    dabwriter.writerow(properLabels)
    for cell in dabDataset:
        dabwriter.writerow(cell.flatten())
        
with open('data/tposes.csv', 'w+') as tposecsv:
    tposewriter = csv.writer(tposecsv, delimiter=',')
    tposewriter.writerow(properLabels)
    for cell in tposeDataset:
        tposewriter.writerow(cell.flatten())
        
with open('data/other.csv', 'w+') as othercsv:
    otherwriter = csv.writer(othercsv, delimiter=',')
    otherwriter.writerow(properLabels)
    for cell in otherDataset:
        otherwriter.writerow(cell.flatten())

# Creating a Labeled Dataset for Training and Testing
# We'll use 0 for other poses, 1 for dabs, and 2 for tposes.

In [9]:
labels = np.zeros(len(otherDataset))
labels = np.append(labels, np.full((len(dabDataset)), 1))
labels = np.append(labels, np.full((len(tposeDataset)), 2))
print(labels)
print("%i total examples for training." % len(labels))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2.]
56 total examples for training.


In [10]:
dataset = np.append(otherDataset, dabDataset, axis=0)
dataset = np.append(dataset, tposeDataset, axis=0)
print(dataset)

[[[488.3213     147.51425      0.83340967]
  [494.22372    284.5734       0.8012297 ]
  [386.4863     270.83716      0.66853976]
  ...
  [  0.           0.           0.        ]
  [  0.           0.           0.        ]
  [  0.           0.           0.        ]]

 [[515.7737     112.18818      0.83487195]
  [478.48004    274.7029       0.8005627 ]
  [368.77948    257.2105       0.6782713 ]
  ...
  [  0.           0.           0.        ]
  [  0.           0.           0.        ]
  [  0.           0.           0.        ]]

 [[547.1316     112.15151      0.79948723]
  [464.79065    268.88403      0.73338044]
  [360.98135    243.43745      0.62600124]
  ...
  [  0.           0.           0.        ]
  [  0.           0.           0.        ]
  [  0.           0.           0.        ]]

 ...

 [[509.97504    257.06958      0.892523  ]
  [460.9663     351.17117      0.7867987 ]
  [372.75305    333.54434      0.6111988 ]
  ...
  [  0.           0.           0.        ]
  [  0.           

In [11]:
dataset.shape

(56, 25, 3)

In [12]:
dataset[:,:,1] / 1280

array([[0.11524551, 0.22232297, 0.21159153, ..., 0.        , 0.        ,
        0.        ],
       [0.08764701, 0.21461165, 0.2009457 , ..., 0.        , 0.        ,
        0.        ],
       [0.08761837, 0.21006565, 0.19018552, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.20083562, 0.2743525 , 0.26058152, ..., 0.        , 0.        ,
        0.        ],
       [0.2238348 , 0.29272196, 0.27588812, ..., 0.        , 0.        ,
        0.        ],
       [0.2100658 , 0.28972745, 0.2758514 , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

# Shuffle labels and features

In [13]:
from sklearn.utils import shuffle
X, y = shuffle(dataset, labels)
from keras.utils.np_utils import to_categorical
y = to_categorical(y, 3)
print(y.shape[1])

Using TensorFlow backend.


3


In [14]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.optimizers import SGD

In [15]:
X = X.reshape(len(X), 75)
dataset[0]

array([[4.88321289e+02, 1.47514252e+02, 8.33409667e-01],
       [4.94223724e+02, 2.84573395e+02, 8.01229715e-01],
       [3.86486298e+02, 2.70837158e+02, 6.68539762e-01],
       [3.37498718e+02, 4.31440033e+02, 8.06459844e-01],
       [2.76727325e+02, 5.92155334e+02, 6.95721209e-01],
       [6.01926575e+02, 2.96297577e+02, 6.77372575e-01],
       [6.17621460e+02, 4.47154175e+02, 8.15527081e-01],
       [6.33207092e+02, 6.13721497e+02, 7.50288665e-01],
       [4.49166534e+02, 6.23515259e+02, 3.33123893e-01],
       [3.68768433e+02, 6.15664124e+02, 2.96909660e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.29464417e+02, 6.35266663e+02, 3.00662249e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.72626495e+02, 1.25848732e+02, 7.93599010e-01],
       [5.09897217e+02, 1.25915306e+02, 8.75047982e-01],
       [4.47158661e+02, 1.31820

In [16]:
model = Sequential()
model.add(Dense(128, activation = 'relu', input_shape = (75,)))
model.add(Dropout(0.5))
model.add(Dense(128, activation = 'relu'))
model.add(Dropout(0.5))
model.add(Dense(y.shape[1], activation = 'softmax'))
model.compile(optimizer = SGD(lr = 0.005),
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])
model.fit(X, y, epochs = 200, batch_size = 64)

Epoch 1/200
56/56 [==============================] - 1s 11ms/step - loss: 249.3411 - accuracy: 0.3393
Epoch 2/200
56/56 [==============================] - 0s 117us/step - loss: 2490.9739 - accuracy: 0.2857
Epoch 3/200
56/56 [==============================] - 0s 111us/step - loss: 11526.4424 - accuracy: 0.2857
Epoch 4/200
56/56 [==============================] - 0s 111us/step - loss: 68494.3672 - accuracy: 0.4286
Epoch 5/200
56/56 [==============================] - 0s 103us/step - loss: 145780.7031 - accuracy: 0.3036
Epoch 6/200
56/56 [==============================] - 0s 108us/step - loss: 1.0723 - accuracy: 0.4643
Epoch 7/200
56/56 [==============================] - 0s 106us/step - loss: 1.1255 - accuracy: 0.4643
Epoch 8/200
56/56 [==============================] - 0s 104us/step - loss: 1.0900 - accuracy: 0.4643
Epoch 9/200
56/56 [==============================] - 0s 113us/step - loss: 1.0832 - accuracy: 0.4643
Epoch 10/200
56/56 [==============================] - 0s 111us/step - loss

Epoch 82/200
56/56 [==============================] - 0s 105us/step - loss: 1.0897 - accuracy: 0.4643
Epoch 83/200
56/56 [==============================] - 0s 110us/step - loss: 1.0896 - accuracy: 0.4643
Epoch 84/200
56/56 [==============================] - 0s 101us/step - loss: 1.0895 - accuracy: 0.4643
Epoch 85/200
56/56 [==============================] - 0s 91us/step - loss: 1.0894 - accuracy: 0.4643
Epoch 86/200
56/56 [==============================] - 0s 95us/step - loss: 1.0893 - accuracy: 0.4643
Epoch 87/200
56/56 [==============================] - 0s 96us/step - loss: 1.0892 - accuracy: 0.4643
Epoch 88/200
56/56 [==============================] - 0s 94us/step - loss: 1.0891 - accuracy: 0.4643
Epoch 89/200
56/56 [==============================] - 0s 94us/step - loss: 1.0890 - accuracy: 0.4643
Epoch 90/200
56/56 [==============================] - 0s 99us/step - loss: 1.0889 - accuracy: 0.4643
Epoch 91/200
56/56 [==============================] - 0s 103us/step - loss: 1.0888 - acc

Epoch 163/200
56/56 [==============================] - 0s 107us/step - loss: 1.0825 - accuracy: 0.4643
Epoch 164/200
56/56 [==============================] - 0s 106us/step - loss: 1.0824 - accuracy: 0.4643
Epoch 165/200
56/56 [==============================] - 0s 101us/step - loss: 1.0824 - accuracy: 0.4643
Epoch 166/200
56/56 [==============================] - 0s 99us/step - loss: 1.0823 - accuracy: 0.4643
Epoch 167/200
56/56 [==============================] - 0s 101us/step - loss: 1.0822 - accuracy: 0.4643
Epoch 168/200
56/56 [==============================] - 0s 117us/step - loss: 1.0821 - accuracy: 0.4643
Epoch 169/200
56/56 [==============================] - 0s 100us/step - loss: 1.0820 - accuracy: 0.4643
Epoch 170/200
56/56 [==============================] - 0s 104us/step - loss: 1.0820 - accuracy: 0.4643
Epoch 171/200
56/56 [==============================] - 0s 96us/step - loss: 1.0819 - accuracy: 0.4643
Epoch 172/200
56/56 [==============================] - 0s 103us/step - loss

# Cleaning up data further¶

## accuracy too low

In [17]:
# let's fit x and y to 0 ~ 1
X, y = shuffle(dataset, labels)
y = to_categorical(y, 3)
print(X.shape)
X[:,:,0] = X[:,:,0] / 720 
X[:,:,1] = X[:,:,1] / 1280
X = X[:,:,:2]
print(X.shape)
X = X.reshape(56, 50)     
print(X.shape)

(56, 25, 3)
(56, 25, 2)
(56, 50)


In [18]:
model = Sequential()
model.add(Dense(128, activation='relu', input_shape=(50,)))
model.add(Dropout(0.5))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(optimizer='Adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X, y, epochs=200,batch_size=64)

Epoch 1/200
56/56 [==============================] - 1s 16ms/step - loss: 1.1644 - accuracy: 0.2143
Epoch 2/200
56/56 [==============================] - 0s 103us/step - loss: 1.1428 - accuracy: 0.2679
Epoch 3/200
56/56 [==============================] - 0s 105us/step - loss: 1.1320 - accuracy: 0.3214
Epoch 4/200
56/56 [==============================] - 0s 117us/step - loss: 1.1374 - accuracy: 0.3036
Epoch 5/200
56/56 [==============================] - 0s 110us/step - loss: 1.0393 - accuracy: 0.4286
Epoch 6/200
56/56 [==============================] - 0s 114us/step - loss: 1.1433 - accuracy: 0.2857
Epoch 7/200
56/56 [==============================] - 0s 133us/step - loss: 1.0965 - accuracy: 0.3750
Epoch 8/200
56/56 [==============================] - 0s 121us/step - loss: 1.0730 - accuracy: 0.4286
Epoch 9/200
56/56 [==============================] - 0s 117us/step - loss: 1.0991 - accuracy: 0.4107
Epoch 10/200
56/56 [==============================] - 0s 146us/step - loss: 1.0500 - accurac

Epoch 82/200
56/56 [==============================] - 0s 113us/step - loss: 0.6708 - accuracy: 0.7500
Epoch 83/200
56/56 [==============================] - 0s 128us/step - loss: 0.6064 - accuracy: 0.8214
Epoch 84/200
56/56 [==============================] - 0s 112us/step - loss: 0.6223 - accuracy: 0.8929
Epoch 85/200
56/56 [==============================] - 0s 118us/step - loss: 0.6217 - accuracy: 0.7679
Epoch 86/200
56/56 [==============================] - 0s 118us/step - loss: 0.6947 - accuracy: 0.7500
Epoch 87/200
56/56 [==============================] - 0s 111us/step - loss: 0.6111 - accuracy: 0.8393
Epoch 88/200
56/56 [==============================] - 0s 114us/step - loss: 0.6252 - accuracy: 0.7857
Epoch 89/200
56/56 [==============================] - 0s 111us/step - loss: 0.6543 - accuracy: 0.8036
Epoch 90/200
56/56 [==============================] - 0s 102us/step - loss: 0.7214 - accuracy: 0.6964
Epoch 91/200
56/56 [==============================] - 0s 110us/step - loss: 0.6845

Epoch 162/200
56/56 [==============================] - 0s 105us/step - loss: 0.3208 - accuracy: 0.8750
Epoch 163/200
56/56 [==============================] - 0s 107us/step - loss: 0.3250 - accuracy: 0.8929
Epoch 164/200
56/56 [==============================] - 0s 105us/step - loss: 0.3684 - accuracy: 0.8214
Epoch 165/200
56/56 [==============================] - 0s 108us/step - loss: 0.3043 - accuracy: 0.9107
Epoch 166/200
56/56 [==============================] - 0s 108us/step - loss: 0.3365 - accuracy: 0.8393
Epoch 167/200
56/56 [==============================] - 0s 115us/step - loss: 0.3274 - accuracy: 0.8214
Epoch 168/200
56/56 [==============================] - 0s 114us/step - loss: 0.3184 - accuracy: 0.9107
Epoch 169/200
56/56 [==============================] - 0s 106us/step - loss: 0.3670 - accuracy: 0.8214
Epoch 170/200
56/56 [==============================] - 0s 110us/step - loss: 0.3388 - accuracy: 0.8571
Epoch 171/200
56/56 [==============================] - 0s 107us/step - lo

# Adding More Data and Beginning Data Augmentation

In [19]:
dabDataset = np.load('data/more-dabs.npy')
tposeDataset = np.load('data/more-tposes.npy')
otherDataset = np.load('data/more-other.npy')
labels1 = np.zeros(len(otherDataset))
labels1 = np.append(labels1, np.full((len(dabDataset)), 1))
labels1 = np.append(labels1, np.full((len(tposeDataset)), 2))
print(labels1)
print("%i total new samples" % len(labels1))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2.]
171 total new samples


In [20]:
dataset1 = np.append(otherDataset, dabDataset, axis=0)
dataset1 = np.append(dataset1, tposeDataset, axis=0)
X1, y1 = shuffle(dataset1, labels1)
y1 = to_categorical(y1, 3)
print(X1.shape)
X1[:,:,0] = X1[:,:,0] / 720
X1[:,:,1] = X1[:,:,1] / 1280
X1 = X1[:,:,:2]
print(X1.shape)
X1 = X1.reshape(len(X1), 50)    
print(X1.shape)

(171, 25, 3)
(171, 25, 2)
(171, 50)


In [21]:
model = Sequential()
model.add(Dense(128, activation = 'relu', input_shape = (50,)))
model.add(Dropout(0.5))
model.add(Dense(128, activation = 'relu'))
model.add(Dropout(0.5))
model.add(Dense(y.shape[1], activation = 'softmax'))
model.compile(optimizer = 'Adam',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])
model.fit(X1, y1, epochs = 2000,batch_size = 64)

Epoch 1/2000
171/171 [==============================] - 1s 5ms/step - loss: 1.1761 - accuracy: 0.3099
Epoch 2/2000
171/171 [==============================] - 0s 122us/step - loss: 1.1267 - accuracy: 0.3860
Epoch 3/2000
171/171 [==============================] - 0s 131us/step - loss: 1.0497 - accuracy: 0.3977
Epoch 4/2000
171/171 [==============================] - 0s 123us/step - loss: 1.0602 - accuracy: 0.4444
Epoch 5/2000
171/171 [==============================] - 0s 136us/step - loss: 1.0370 - accuracy: 0.4678
Epoch 6/2000
171/171 [==============================] - 0s 162us/step - loss: 1.0589 - accuracy: 0.4035
Epoch 7/2000
171/171 [==============================] - 0s 174us/step - loss: 1.0220 - accuracy: 0.4737
Epoch 8/2000
171/171 [==============================] - 0s 173us/step - loss: 1.0328 - accuracy: 0.4854
Epoch 9/2000
171/171 [==============================] - 0s 158us/step - loss: 1.0327 - accuracy: 0.5029
Epoch 10/2000
171/171 [==============================] - 0s 151us/

171/171 [==============================] - 0s 133us/step - loss: 0.2434 - accuracy: 0.9064
Epoch 80/2000
171/171 [==============================] - 0s 125us/step - loss: 0.1792 - accuracy: 0.9415
Epoch 81/2000
171/171 [==============================] - 0s 120us/step - loss: 0.1778 - accuracy: 0.9474
Epoch 82/2000
171/171 [==============================] - 0s 114us/step - loss: 0.1923 - accuracy: 0.9357
Epoch 83/2000
171/171 [==============================] - 0s 106us/step - loss: 0.1957 - accuracy: 0.9474
Epoch 84/2000
171/171 [==============================] - 0s 104us/step - loss: 0.1781 - accuracy: 0.9474
Epoch 85/2000
171/171 [==============================] - 0s 110us/step - loss: 0.1661 - accuracy: 0.9415
Epoch 86/2000
171/171 [==============================] - 0s 111us/step - loss: 0.1629 - accuracy: 0.9415
Epoch 87/2000
171/171 [==============================] - 0s 110us/step - loss: 0.1820 - accuracy: 0.9532
Epoch 88/2000
171/171 [==============================] - 0s 107us/ste

171/171 [==============================] - 0s 110us/step - loss: 0.0500 - accuracy: 0.9825
Epoch 157/2000
171/171 [==============================] - 0s 108us/step - loss: 0.0698 - accuracy: 0.9825
Epoch 158/2000
171/171 [==============================] - 0s 113us/step - loss: 0.0460 - accuracy: 1.0000
Epoch 159/2000
171/171 [==============================] - 0s 106us/step - loss: 0.0566 - accuracy: 0.9883
Epoch 160/2000
171/171 [==============================] - 0s 102us/step - loss: 0.0716 - accuracy: 0.9766
Epoch 161/2000
171/171 [==============================] - 0s 106us/step - loss: 0.0585 - accuracy: 0.9766
Epoch 162/2000
171/171 [==============================] - 0s 106us/step - loss: 0.0432 - accuracy: 0.9942
Epoch 163/2000
171/171 [==============================] - 0s 105us/step - loss: 0.0447 - accuracy: 0.9942
Epoch 164/2000
171/171 [==============================] - 0s 101us/step - loss: 0.0641 - accuracy: 0.9766
Epoch 165/2000
171/171 [==============================] - 0s 

171/171 [==============================] - 0s 110us/step - loss: 0.0240 - accuracy: 0.9942
Epoch 234/2000
171/171 [==============================] - 0s 119us/step - loss: 0.0344 - accuracy: 0.9883
Epoch 235/2000
171/171 [==============================] - 0s 149us/step - loss: 0.0350 - accuracy: 0.9883
Epoch 236/2000
171/171 [==============================] - 0s 117us/step - loss: 0.0464 - accuracy: 0.9766
Epoch 237/2000
171/171 [==============================] - 0s 111us/step - loss: 0.0253 - accuracy: 0.9942
Epoch 238/2000
171/171 [==============================] - 0s 108us/step - loss: 0.0161 - accuracy: 1.0000
Epoch 239/2000
171/171 [==============================] - 0s 109us/step - loss: 0.0310 - accuracy: 0.9883
Epoch 240/2000
171/171 [==============================] - 0s 107us/step - loss: 0.0187 - accuracy: 1.0000
Epoch 241/2000
171/171 [==============================] - 0s 110us/step - loss: 0.0193 - accuracy: 1.0000
Epoch 242/2000
171/171 [==============================] - 0s 

171/171 [==============================] - 0s 108us/step - loss: 0.0090 - accuracy: 1.0000
Epoch 311/2000
171/171 [==============================] - 0s 111us/step - loss: 0.0125 - accuracy: 1.0000
Epoch 312/2000
171/171 [==============================] - 0s 108us/step - loss: 0.0075 - accuracy: 1.0000
Epoch 313/2000
171/171 [==============================] - 0s 110us/step - loss: 0.0062 - accuracy: 1.0000
Epoch 314/2000
171/171 [==============================] - 0s 106us/step - loss: 0.0152 - accuracy: 0.9942
Epoch 315/2000
171/171 [==============================] - 0s 108us/step - loss: 0.0149 - accuracy: 1.0000
Epoch 316/2000
171/171 [==============================] - 0s 109us/step - loss: 0.0193 - accuracy: 1.0000
Epoch 317/2000
171/171 [==============================] - 0s 111us/step - loss: 0.0187 - accuracy: 0.9883
Epoch 318/2000
171/171 [==============================] - 0s 107us/step - loss: 0.0126 - accuracy: 0.9942
Epoch 319/2000
171/171 [==============================] - 0s 

171/171 [==============================] - 0s 107us/step - loss: 0.0301 - accuracy: 0.9883
Epoch 388/2000
171/171 [==============================] - 0s 113us/step - loss: 0.0079 - accuracy: 1.0000
Epoch 389/2000
171/171 [==============================] - 0s 105us/step - loss: 0.0056 - accuracy: 1.0000
Epoch 390/2000
171/171 [==============================] - 0s 111us/step - loss: 0.0103 - accuracy: 1.0000
Epoch 391/2000
171/171 [==============================] - 0s 120us/step - loss: 0.0109 - accuracy: 1.0000
Epoch 392/2000
171/171 [==============================] - 0s 108us/step - loss: 0.0082 - accuracy: 1.0000
Epoch 393/2000
171/171 [==============================] - 0s 110us/step - loss: 0.0077 - accuracy: 1.0000
Epoch 394/2000
171/171 [==============================] - 0s 108us/step - loss: 0.0115 - accuracy: 1.0000
Epoch 395/2000
171/171 [==============================] - 0s 105us/step - loss: 0.0102 - accuracy: 1.0000
Epoch 396/2000
171/171 [==============================] - 0s 

171/171 [==============================] - 0s 102us/step - loss: 0.0074 - accuracy: 1.0000
Epoch 465/2000
171/171 [==============================] - 0s 104us/step - loss: 0.0198 - accuracy: 0.9942
Epoch 466/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0086 - accuracy: 1.0000
Epoch 467/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0068 - accuracy: 1.0000
Epoch 468/2000
171/171 [==============================] - 0s 102us/step - loss: 0.0043 - accuracy: 1.0000
Epoch 469/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0053 - accuracy: 1.0000
Epoch 470/2000
171/171 [==============================] - 0s 102us/step - loss: 0.0104 - accuracy: 1.0000
Epoch 471/2000
171/171 [==============================] - 0s 103us/step - loss: 0.0053 - accuracy: 1.0000
Epoch 472/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0077 - accuracy: 1.0000
Epoch 473/2000
171/171 [==============================] - 0s 

171/171 [==============================] - 0s 101us/step - loss: 0.0016 - accuracy: 1.0000
Epoch 542/2000
171/171 [==============================] - 0s 103us/step - loss: 0.0051 - accuracy: 1.0000
Epoch 543/2000
171/171 [==============================] - 0s 102us/step - loss: 0.0020 - accuracy: 1.0000
Epoch 544/2000
171/171 [==============================] - 0s 102us/step - loss: 0.0079 - accuracy: 1.0000
Epoch 545/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0022 - accuracy: 1.0000
Epoch 546/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0097 - accuracy: 0.9942
Epoch 547/2000
171/171 [==============================] - 0s 97us/step - loss: 0.0032 - accuracy: 1.0000
Epoch 548/2000
171/171 [==============================] - 0s 105us/step - loss: 0.0020 - accuracy: 1.0000
Epoch 549/2000
171/171 [==============================] - 0s 108us/step - loss: 0.0114 - accuracy: 1.0000
Epoch 550/2000
171/171 [==============================] - 0s 10

171/171 [==============================] - 0s 107us/step - loss: 0.0012 - accuracy: 1.0000
Epoch 619/2000
171/171 [==============================] - 0s 108us/step - loss: 0.0078 - accuracy: 1.0000
Epoch 620/2000
171/171 [==============================] - 0s 105us/step - loss: 0.0016 - accuracy: 1.0000
Epoch 621/2000
171/171 [==============================] - 0s 106us/step - loss: 0.0024 - accuracy: 1.0000
Epoch 622/2000
171/171 [==============================] - 0s 107us/step - loss: 0.0105 - accuracy: 0.9942
Epoch 623/2000
171/171 [==============================] - 0s 109us/step - loss: 0.0042 - accuracy: 1.0000
Epoch 624/2000
171/171 [==============================] - 0s 104us/step - loss: 0.0083 - accuracy: 0.9942
Epoch 625/2000
171/171 [==============================] - 0s 106us/step - loss: 0.0029 - accuracy: 1.0000
Epoch 626/2000
171/171 [==============================] - 0s 107us/step - loss: 0.0088 - accuracy: 0.9942
Epoch 627/2000
171/171 [==============================] - 0s 

171/171 [==============================] - 0s 99us/step - loss: 0.0079 - accuracy: 0.9942
Epoch 696/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0045 - accuracy: 1.0000
Epoch 697/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0021 - accuracy: 1.0000
Epoch 698/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0010 - accuracy: 1.0000
Epoch 699/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0059 - accuracy: 1.0000
Epoch 700/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0027 - accuracy: 1.0000
Epoch 701/2000
171/171 [==============================] - 0s 101us/step - loss: 0.0186 - accuracy: 0.9883
Epoch 702/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0122 - accuracy: 0.9942
Epoch 703/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0057 - accuracy: 1.0000
Epoch 704/2000
171/171 [==============================] - 0s 98us/

171/171 [==============================] - 0s 108us/step - loss: 0.0033 - accuracy: 1.0000
Epoch 773/2000
171/171 [==============================] - 0s 104us/step - loss: 0.0011 - accuracy: 1.0000
Epoch 774/2000
171/171 [==============================] - 0s 102us/step - loss: 0.0035 - accuracy: 1.0000
Epoch 775/2000
171/171 [==============================] - 0s 101us/step - loss: 0.0170 - accuracy: 0.9942
Epoch 776/2000
171/171 [==============================] - 0s 101us/step - loss: 8.1471e-04 - accuracy: 1.0000
Epoch 777/2000
171/171 [==============================] - 0s 103us/step - loss: 0.0061 - accuracy: 1.0000
Epoch 778/2000
171/171 [==============================] - 0s 100us/step - loss: 9.4401e-04 - accuracy: 1.0000
Epoch 779/2000
171/171 [==============================] - 0s 102us/step - loss: 0.0088 - accuracy: 0.9942
Epoch 780/2000
171/171 [==============================] - 0s 103us/step - loss: 0.0028 - accuracy: 1.0000
Epoch 781/2000
171/171 [=============================

171/171 [==============================] - 0s 101us/step - loss: 6.3916e-04 - accuracy: 1.0000
Epoch 850/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0014 - accuracy: 1.0000
Epoch 851/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0023 - accuracy: 1.0000
Epoch 852/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0021 - accuracy: 1.0000
Epoch 853/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0088 - accuracy: 0.9942
Epoch 854/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0049 - accuracy: 1.0000
Epoch 855/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0024 - accuracy: 1.0000
Epoch 856/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0036 - accuracy: 1.0000
Epoch 857/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0051 - accuracy: 1.0000
Epoch 858/2000
171/171 [==============================] - 0s

171/171 [==============================] - 0s 232us/step - loss: 0.0015 - accuracy: 1.0000
Epoch 927/2000
171/171 [==============================] - 0s 133us/step - loss: 0.0037 - accuracy: 1.0000
Epoch 928/2000
171/171 [==============================] - 0s 115us/step - loss: 7.2988e-04 - accuracy: 1.0000
Epoch 929/2000
171/171 [==============================] - 0s 110us/step - loss: 0.0048 - accuracy: 1.0000
Epoch 930/2000
171/171 [==============================] - 0s 117us/step - loss: 0.0224 - accuracy: 0.9942
Epoch 931/2000
171/171 [==============================] - 0s 112us/step - loss: 0.0063 - accuracy: 1.0000
Epoch 932/2000
171/171 [==============================] - 0s 119us/step - loss: 0.0101 - accuracy: 0.9942
Epoch 933/2000
171/171 [==============================] - 0s 112us/step - loss: 0.0070 - accuracy: 1.0000
Epoch 934/2000
171/171 [==============================] - 0s 113us/step - loss: 0.0074 - accuracy: 1.0000
Epoch 935/2000
171/171 [==============================] -

171/171 [==============================] - 0s 102us/step - loss: 0.0021 - accuracy: 1.0000
Epoch 1004/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0037 - accuracy: 1.0000
Epoch 1005/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0057 - accuracy: 1.0000
Epoch 1006/2000
171/171 [==============================] - 0s 106us/step - loss: 0.0011 - accuracy: 1.0000
Epoch 1007/2000
171/171 [==============================] - 0s 116us/step - loss: 2.6307e-04 - accuracy: 1.0000
Epoch 1008/2000
171/171 [==============================] - 0s 129us/step - loss: 7.6928e-04 - accuracy: 1.0000
Epoch 1009/2000
171/171 [==============================] - 0s 119us/step - loss: 0.0105 - accuracy: 1.0000
Epoch 1010/2000
171/171 [==============================] - 0s 116us/step - loss: 0.0080 - accuracy: 0.9942
Epoch 1011/2000
171/171 [==============================] - 0s 120us/step - loss: 0.0024 - accuracy: 1.0000
Epoch 1012/2000
171/171 [====================

171/171 [==============================] - 0s 123us/step - loss: 0.0062 - accuracy: 1.0000
Epoch 1080/2000
171/171 [==============================] - 0s 109us/step - loss: 0.0061 - accuracy: 0.9942
Epoch 1081/2000
171/171 [==============================] - 0s 108us/step - loss: 0.0050 - accuracy: 1.0000
Epoch 1082/2000
171/171 [==============================] - 0s 106us/step - loss: 0.0125 - accuracy: 0.9942
Epoch 1083/2000
171/171 [==============================] - 0s 107us/step - loss: 0.0024 - accuracy: 1.0000
Epoch 1084/2000
171/171 [==============================] - 0s 111us/step - loss: 0.0103 - accuracy: 0.9942
Epoch 1085/2000
171/171 [==============================] - 0s 112us/step - loss: 0.0105 - accuracy: 1.0000
Epoch 1086/2000
171/171 [==============================] - 0s 114us/step - loss: 0.0054 - accuracy: 1.0000
Epoch 1087/2000
171/171 [==============================] - 0s 115us/step - loss: 0.0031 - accuracy: 1.0000
Epoch 1088/2000
171/171 [============================

171/171 [==============================] - 0s 114us/step - loss: 0.0018 - accuracy: 1.0000
Epoch 1156/2000
171/171 [==============================] - 0s 108us/step - loss: 0.0141 - accuracy: 0.9942
Epoch 1157/2000
171/171 [==============================] - 0s 113us/step - loss: 0.0010 - accuracy: 1.0000
Epoch 1158/2000
171/171 [==============================] - 0s 105us/step - loss: 0.0086 - accuracy: 0.9942
Epoch 1159/2000
171/171 [==============================] - 0s 111us/step - loss: 7.3952e-04 - accuracy: 1.0000
Epoch 1160/2000
171/171 [==============================] - 0s 102us/step - loss: 7.3380e-04 - accuracy: 1.0000
Epoch 1161/2000
171/171 [==============================] - 0s 103us/step - loss: 0.0046 - accuracy: 0.9942
Epoch 1162/2000
171/171 [==============================] - 0s 115us/step - loss: 0.0057 - accuracy: 1.0000
Epoch 1163/2000
171/171 [==============================] - 0s 111us/step - loss: 0.0104 - accuracy: 0.9942
Epoch 1164/2000
171/171 [====================

171/171 [==============================] - 0s 102us/step - loss: 2.9124e-04 - accuracy: 1.0000
Epoch 1232/2000
171/171 [==============================] - 0s 101us/step - loss: 0.0062 - accuracy: 0.9942
Epoch 1233/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0105 - accuracy: 0.9942
Epoch 1234/2000
171/171 [==============================] - 0s 99us/step - loss: 5.5919e-04 - accuracy: 1.0000
Epoch 1235/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0019 - accuracy: 1.0000
Epoch 1236/2000
171/171 [==============================] - 0s 108us/step - loss: 0.0027 - accuracy: 1.0000
Epoch 1237/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0012 - accuracy: 1.0000
Epoch 1238/2000
171/171 [==============================] - 0s 101us/step - loss: 9.2576e-04 - accuracy: 1.0000
Epoch 1239/2000
171/171 [==============================] - 0s 101us/step - loss: 0.0011 - accuracy: 1.0000
Epoch 1240/2000
171/171 [===================

171/171 [==============================] - 0s 101us/step - loss: 0.0012 - accuracy: 1.0000
Epoch 1308/2000
171/171 [==============================] - 0s 99us/step - loss: 7.5043e-04 - accuracy: 1.0000
Epoch 1309/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0017 - accuracy: 1.0000
Epoch 1310/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0072 - accuracy: 0.9942
Epoch 1311/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0011 - accuracy: 1.0000
Epoch 1312/2000
171/171 [==============================] - 0s 99us/step - loss: 5.1263e-04 - accuracy: 1.0000
Epoch 1313/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0023 - accuracy: 1.0000
Epoch 1314/2000
171/171 [==============================] - 0s 103us/step - loss: 7.3108e-04 - accuracy: 1.0000
Epoch 1315/2000
171/171 [==============================] - 0s 104us/step - loss: 0.0011 - accuracy: 1.0000
Epoch 1316/2000
171/171 [=====================

171/171 [==============================] - 0s 99us/step - loss: 0.0028 - accuracy: 1.0000
Epoch 1384/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0157 - accuracy: 0.9942
Epoch 1385/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0015 - accuracy: 1.0000
Epoch 1386/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0013 - accuracy: 1.0000
Epoch 1387/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0032 - accuracy: 1.0000
Epoch 1388/2000
171/171 [==============================] - 0s 97us/step - loss: 0.0090 - accuracy: 0.9942
Epoch 1389/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0015 - accuracy: 1.0000
Epoch 1390/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0137 - accuracy: 0.9942
Epoch 1391/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0155 - accuracy: 0.9942
Epoch 1392/2000
171/171 [==============================] - 0s

171/171 [==============================] - 0s 98us/step - loss: 0.0026 - accuracy: 1.0000
Epoch 1460/2000
171/171 [==============================] - 0s 98us/step - loss: 2.9296e-04 - accuracy: 1.0000
Epoch 1461/2000
171/171 [==============================] - 0s 98us/step - loss: 5.1883e-04 - accuracy: 1.0000
Epoch 1462/2000
171/171 [==============================] - 0s 100us/step - loss: 3.7641e-04 - accuracy: 1.0000
Epoch 1463/2000
171/171 [==============================] - 0s 99us/step - loss: 4.2399e-04 - accuracy: 1.0000
Epoch 1464/2000
171/171 [==============================] - 0s 97us/step - loss: 0.0052 - accuracy: 1.0000
Epoch 1465/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0093 - accuracy: 0.9942
Epoch 1466/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0014 - accuracy: 1.0000
Epoch 1467/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0015 - accuracy: 1.0000
Epoch 1468/2000
171/171 [====================

171/171 [==============================] - 0s 100us/step - loss: 0.0019 - accuracy: 1.0000
Epoch 1536/2000
171/171 [==============================] - 0s 101us/step - loss: 0.0030 - accuracy: 1.0000
Epoch 1537/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0114 - accuracy: 0.9942
Epoch 1538/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0017 - accuracy: 1.0000
Epoch 1539/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0108 - accuracy: 0.9942
Epoch 1540/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0023 - accuracy: 1.0000
Epoch 1541/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0053 - accuracy: 0.9942
Epoch 1542/2000
171/171 [==============================] - 0s 97us/step - loss: 0.0277 - accuracy: 0.9942
Epoch 1543/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0190 - accuracy: 0.9942
Epoch 1544/2000
171/171 [==============================] - 0

171/171 [==============================] - 0s 99us/step - loss: 0.0018 - accuracy: 1.0000
Epoch 1612/2000
171/171 [==============================] - 0s 101us/step - loss: 0.0010 - accuracy: 1.0000
Epoch 1613/2000
171/171 [==============================] - 0s 97us/step - loss: 0.0011 - accuracy: 1.0000
Epoch 1614/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0034 - accuracy: 1.0000
Epoch 1615/2000
171/171 [==============================] - 0s 98us/step - loss: 3.9035e-04 - accuracy: 1.0000
Epoch 1616/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0030 - accuracy: 1.0000
Epoch 1617/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0130 - accuracy: 0.9942
Epoch 1618/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0012 - accuracy: 1.0000
Epoch 1619/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0043 - accuracy: 1.0000
Epoch 1620/2000
171/171 [==============================]

171/171 [==============================] - 0s 99us/step - loss: 0.0012 - accuracy: 1.0000
Epoch 1688/2000
171/171 [==============================] - 0s 108us/step - loss: 0.0011 - accuracy: 1.0000
Epoch 1689/2000
171/171 [==============================] - 0s 127us/step - loss: 2.9396e-04 - accuracy: 1.0000
Epoch 1690/2000
171/171 [==============================] - 0s 119us/step - loss: 0.0047 - accuracy: 1.0000
Epoch 1691/2000
171/171 [==============================] - 0s 112us/step - loss: 0.0014 - accuracy: 1.0000
Epoch 1692/2000
171/171 [==============================] - 0s 107us/step - loss: 0.0396 - accuracy: 0.9883
Epoch 1693/2000
171/171 [==============================] - 0s 107us/step - loss: 0.0107 - accuracy: 0.9942
Epoch 1694/2000
171/171 [==============================] - 0s 104us/step - loss: 0.0070 - accuracy: 0.9942
Epoch 1695/2000
171/171 [==============================] - 0s 110us/step - loss: 0.0016 - accuracy: 1.0000
Epoch 1696/2000
171/171 [=========================

171/171 [==============================] - 0s 110us/step - loss: 6.4506e-04 - accuracy: 1.0000
Epoch 1764/2000
171/171 [==============================] - 0s 109us/step - loss: 0.0013 - accuracy: 1.0000
Epoch 1765/2000
171/171 [==============================] - 0s 120us/step - loss: 6.2365e-04 - accuracy: 1.0000
Epoch 1766/2000
171/171 [==============================] - 0s 128us/step - loss: 2.6077e-04 - accuracy: 1.0000
Epoch 1767/2000
171/171 [==============================] - 0s 116us/step - loss: 3.2266e-04 - accuracy: 1.0000
Epoch 1768/2000
171/171 [==============================] - 0s 111us/step - loss: 2.1621e-04 - accuracy: 1.0000
Epoch 1769/2000
171/171 [==============================] - 0s 109us/step - loss: 3.3519e-04 - accuracy: 1.0000
Epoch 1770/2000
171/171 [==============================] - 0s 114us/step - loss: 0.0022 - accuracy: 1.0000
Epoch 1771/2000
171/171 [==============================] - 0s 110us/step - loss: 0.0014 - accuracy: 1.0000
Epoch 1772/2000
171/171 [====

171/171 [==============================] - 0s 99us/step - loss: 0.0059 - accuracy: 0.9942
Epoch 1839/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0014 - accuracy: 1.0000
Epoch 1840/2000
171/171 [==============================] - 0s 98us/step - loss: 8.7406e-04 - accuracy: 1.0000
Epoch 1841/2000
171/171 [==============================] - 0s 97us/step - loss: 0.0022 - accuracy: 1.0000
Epoch 1842/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0025 - accuracy: 1.0000
Epoch 1843/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0027 - accuracy: 1.0000
Epoch 1844/2000
171/171 [==============================] - 0s 99us/step - loss: 7.8470e-04 - accuracy: 1.0000
Epoch 1845/2000
171/171 [==============================] - 0s 98us/step - loss: 6.1752e-04 - accuracy: 1.0000
Epoch 1846/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0024 - accuracy: 1.0000
Epoch 1847/2000
171/171 [=======================

171/171 [==============================] - 0s 99us/step - loss: 0.0080 - accuracy: 1.0000
Epoch 1915/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0030 - accuracy: 1.0000
Epoch 1916/2000
171/171 [==============================] - 0s 98us/step - loss: 8.5943e-04 - accuracy: 1.0000
Epoch 1917/2000
171/171 [==============================] - 0s 96us/step - loss: 0.0014 - accuracy: 1.0000
Epoch 1918/2000
171/171 [==============================] - 0s 97us/step - loss: 0.0046 - accuracy: 1.0000
Epoch 1919/2000
171/171 [==============================] - 0s 97us/step - loss: 0.0012 - accuracy: 1.0000
Epoch 1920/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0015 - accuracy: 1.0000
Epoch 1921/2000
171/171 [==============================] - 0s 97us/step - loss: 9.7315e-04 - accuracy: 1.0000
Epoch 1922/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0107 - accuracy: 0.9942
Epoch 1923/2000
171/171 [=============================

171/171 [==============================] - 0s 100us/step - loss: 0.0120 - accuracy: 0.9942
Epoch 1991/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0012 - accuracy: 1.0000
Epoch 1992/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0077 - accuracy: 0.9942
Epoch 1993/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0026 - accuracy: 1.0000
Epoch 1994/2000
171/171 [==============================] - 0s 100us/step - loss: 0.0039 - accuracy: 1.0000
Epoch 1995/2000
171/171 [==============================] - 0s 98us/step - loss: 0.0150 - accuracy: 0.9942
Epoch 1996/2000
171/171 [==============================] - 0s 97us/step - loss: 0.0161 - accuracy: 0.9942
Epoch 1997/2000
171/171 [==============================] - 0s 99us/step - loss: 0.0112 - accuracy: 0.9942
Epoch 1998/2000
171/171 [==============================] - 0s 96us/step - loss: 0.0129 - accuracy: 1.0000
Epoch 1999/2000
171/171 [==============================] - 0

In [22]:
model.predict_classes(X)

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0])

In [23]:
y

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1

In [24]:
model.test_on_batch(X, y)

[8.308915, 0.8678414]

In [25]:
model.save('data/dab-tpose-other.h5')

In [26]:
import keras
modello = keras.models.load_model('data/dab-tpose-other.h5')

In [27]:
dabDataset = np.load('data/test-dabs.npy')
dabDataset[:,:,0] = dabDataset[:,:,0] / 720
dabDataset[:,:,1] = dabDataset[:,:,1] / 1280
dabDataset = dabDataset[:,:,:2]
dabDataset = dabDataset.reshape(len(dabDataset), 50)
modello.predict_classes(dabDataset)

array([1, 1, 1, 1, 1, 1])